In [1]:
import numpy as np

In [26]:
def input_matrix(num_rows, num_cols):
    matrix = []
    i = 0
    while i < num_rows:
        try:
            row = list(map(int, input(f"Row {i+1}, enter values separated by space( {num_cols}): ").split()))
            if num_cols != len(row):
                raise ValueError(f"wanted {num_cols} values but got {len(row)} values")
            matrix.append(row)
            i += 1  
        except ValueError as e:
            print(f"Error: {e}. Please re-enter Row {i+1}.")
    return np.array(matrix)

In [ ]:

def matrix_subtraction():
    num_of_row=int(input("Enter number of rows:"))
    num_of_col=int(input("Enter number of columns:"))
    print("Enter the elements of the first matrix:")
    matrix1=input_matrix(num_of_row, num_of_col)
    print(matrix1)
    print("Enter the elements of the second matrix:")
    matrix2=input_matrix(num_of_row, num_of_col)
    print(matrix2)
    print("Subtraction of the two matrices:")
    result=np.zeros((num_of_row, num_of_col))
    for i in range(num_of_row):
        for j in range(num_of_col):
            result[i][j]=matrix1[i][j]-matrix2[i][j]
    print("Subtraction result: ")
    print(result)
if __name__ == "__main__":
    matrix_subtraction()

Enter the elements of the first matrix:
[[1 2 3]
 [1 2 3]]
Enter the elements of the second matrix:
[[1 2 3]
 [5 6 7]]
Subtraction of the two matrices:
[[ 0.  0.  0.]
 [-4. -4. -4.]]


In [ ]:
def scalar_multiplication():
    num_of_row=int(input("Enter number of rows:"))
    num_of_col=int(input("Enter number of columns:"))
    print("Enter the elements of the matrix:")
    matrix=input_matrix(num_of_row, num_of_col)
    print(matrix)
    scalar=int(input("Enter scalar value:"))
    print("Scalar multiplication of the matrix:")
    result=np.ones((num_of_row, num_of_col))
    for i in range(num_of_row):
        for j in range(num_of_col):
            result[i][j]=matrix[i][j]*scalar
    return result

if __name__ == "__main__":
    scalar_multiplication()

Enter the elements of the matrix:
[[1 2 3]
 [4 5 6]]
Scalar multiplication of the matrix:
[[ 7. 14. 21.]
 [28. 35. 42.]]


In [29]:
def row_column_input():
    check=True
    while check:
        try:
            num_of_row=int(input("Enter number of rows:"))
            num_of_col=int(input("Enter number of columns:"))
            check=False
        except ValueError as e:
            print(f"Error: {e}.")
    return (num_of_row, num_of_col)

def matrix_multiplication():
    first_matrix_row, first_matrix_column= row_column_input()
    print("Enter the elements of the first matrix:")
    matrix1=input_matrix(first_matrix_row, first_matrix_column)
    print(matrix1)
    second_matrix_row, second_matrix_column= row_column_input()
    print("Enter the elements of the second matrix:")
    matrix2=input_matrix(second_matrix_row, second_matrix_column)
    if first_matrix_column == second_matrix_row:
        result=np.ones((first_matrix_row, second_matrix_column))
        for i in range(first_matrix_row):
            for j in range(second_matrix_column):
                result[i][j]=sum([i * j for i, j in zip(matrix1[i,:], matrix2[:,j])])
        print("Result of multiplication is: ")
        print(result)
    else:
        print("Dimension mismatch, Multiplication not possible")

if __name__ == "__main__":
    matrix_multiplication()

Enter the elements of the first matrix:
[[2 1 3]
 [3 1 2]]
Enter the elements of the second matrix:
Result of multiplication is: 
[[20. 26.]
 [16. 22.]]


In [ ]:
def transpose_matrix():
    rows,cols=row_column_input()
    print("Enter the elements of the first matrix:")
    matrix=input_matrix(rows, cols)
    print(matrix)
    transposed = np.zeros((cols, rows), dtype=int)
    for j in range(cols):
        for i in range(rows):
            transposed[j][i] = matrix[i][j]
    return transposed
transpose_matrix()

Enter the elements of the first matrix:
[[1 2 3]
 [2 4 5]]


array([[1, 2],
       [2, 4],
       [3, 5]])

In [ ]:
def is_identity_matrix():
    rows,cols=row_column_input()
    print("Enter the elements of the first matrix:")
    matrix=input_matrix(rows, cols)
    print(matrix)
    if rows != cols:
        return False
    
    for i in range(rows):
        for j in range(cols):
            if i == j:
                if matrix[i][j] != 1:  
                    return False
            else:
                if matrix[i][j] != 0: 
                    return False
    return True

if __name__ == "__main__":
    if is_identity_matrix():
        print("The matrix is an identity matrix.")
    else:
        print("The matrix is not an identity matrix.")
