In [2]:
print("hello world")

hello world


In [3]:
import numpy as np

In [4]:
num=np.array([1,2,3,4,5,6,7,8,9])

In [5]:
num

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
num.shape

(9,)

In [ ]:
num.ndim  #dimension bole

1

In [8]:
num2d=num.reshape(3,3)

In [9]:
num2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
num2d.ndim

2

In [11]:
num2d.shape

(3, 3)

In [14]:
ones_mat=np.ones((3,3))
ones_mat

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [16]:
zeromat=np.zeros((4,3))
zeromat

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
zeromat=np.zeros((4,3),dtype=int)
zeromat

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [19]:
identity=np.eye(3)
identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
identity=np.eye(3,3,dtype=int)
identity

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
emptymat=np.empty((4,3))
emptymat

array([[1.11107410e-311, 2.81617418e-322, 0.00000000e+000],
       [0.00000000e+000, 3.11525958e-307, 5.64233733e-067],
       [5.58530643e-091, 2.65066740e-032, 5.54536033e+169],
       [1.67535738e-076, 6.48224660e+170, 4.93432906e+257]])

In [35]:
num2d_transpose=num2d.T
num2d_transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
num2d>3 #boolean indexing

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
num2d[num2d>3]

array([4, 5, 6, 7, 8, 9])

In [56]:
np.random.seed(40)
x1=np.random.randint(1,10,3)
x1

array([7, 8, 6], dtype=int32)

In [55]:
np.random.seed(40)
x1=np.random.randint(1,10,(3,3))
x1

array([[7, 8, 6],
       [9, 9, 3],
       [2, 8, 3]], dtype=int32)

In [57]:
np.random.seed(40)
x1=np.random.randint(1,10,(3,3,5))
x1

array([[[7, 8, 6, 9, 9],
        [3, 2, 8, 3, 4],
        [8, 4, 1, 2, 6]],

       [[9, 5, 5, 9, 7],
        [4, 4, 8, 8, 2],
        [4, 6, 3, 3, 4]],

       [[8, 4, 3, 3, 6],
        [1, 2, 8, 4, 9],
        [6, 4, 3, 7, 4]]], dtype=int32)

In [60]:
x1=np.random.randint(1,10,size=(10))
x1

array([6, 6, 6, 1, 4, 3, 5, 8, 7, 8], dtype=int32)

In [61]:
x1[2:7]

array([6, 1, 4, 3, 5], dtype=int32)

In [62]:
x1[2:7:2]

array([6, 4, 5], dtype=int32)

In [63]:
x1[::-1]

array([8, 7, 8, 5, 3, 4, 1, 6, 6, 6], dtype=int32)

In [64]:
x1[7:2:-1]

array([8, 5, 3, 4, 1], dtype=int32)

In [66]:
x1=np.random.randint(1,10,size=(5,4))
x1

array([[8, 4, 5, 5],
       [8, 3, 1, 9],
       [4, 9, 6, 6],
       [6, 8, 6, 5],
       [1, 4, 5, 7]], dtype=int32)

In [67]:
x1[1:3,1:3]

array([[3, 1],
       [9, 6]], dtype=int32)

In [68]:
x1[:3,:3]

array([[8, 4, 5],
       [8, 3, 1],
       [4, 9, 6]], dtype=int32)

In [69]:
x1[2:,2:]

array([[6, 6],
       [6, 5],
       [5, 7]], dtype=int32)

## python lambda function


In [ ]:
##lambda function
#lambda arguments:expressions
"""
define a lambda function that takes x as an argument nad returnes the value with 10 extra values
"""
x=lambda a:a+10
x(40) 


50

In [ ]:
arr=np.array([1,3,5,7,9])
list(map(lambda x:x**2,arr))

[np.int64(1), np.int64(9), np.int64(25), np.int64(49), np.int64(81)]

In [75]:
arr=[1,3,5,7,9]
list(map(lambda x:x**2,arr))

[1, 9, 25, 49, 81]

In [76]:
arr=np.array([1,3,5,7,9])
np.array(list(map(lambda x:x**2,arr)))

array([ 1,  9, 25, 49, 81])

In [77]:
arr=np.array([1,2,3,4,5,6,7,8,9])
np.array(list(filter(lambda x:x%2==0,arr)))

array([2, 4, 6, 8])

In [85]:
num=np.linspace(0,10,10)
num

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [81]:
num.size

20

In [84]:
num=np.linspace(0,10,20).reshape(5,4)
num

array([[ 0.        ,  0.52631579,  1.05263158,  1.57894737],
       [ 2.10526316,  2.63157895,  3.15789474,  3.68421053],
       [ 4.21052632,  4.73684211,  5.26315789,  5.78947368],
       [ 6.31578947,  6.84210526,  7.36842105,  7.89473684],
       [ 8.42105263,  8.94736842,  9.47368421, 10.        ]])